---
title: "Planning to Plan"
subtitle: "18 Nov. 2025"
author: "Lauren E. Price"
format: 
  revealjs:
    theme: default
---

# Introduction

## Career Path of Problem Solving

- Sociology & Policy Coursework
- Research Assistant
- Quant Training
- Grant Manager, > $60M over 7 years
- Accidentally in Data Science

## Fundamental Goals

- You know more than you think you do.
- Build your tolerance around disorientation
- Move towards being curious, clever... even nosy

## Today, November 18

- Context and initial facts
- Scenario & task at hand
- Exploratory planning: Planning to plan

# Scope

## Houston ISD

- *Independent* defined
- Largest school district in Texas
- Over 300 facilities, over 20,000 employees
- [Geographically enormous](https://resources.finalsite.net/images/v1757703667/houstonisdorg/aq9uxdpyxkbs9ilajh2l/DistrictDivisionsSchoolsandAdministrativeFacilities20252026.pdf)
- $2.1 billion annual budget, about 85% of which is People

## Governance 

- Typically, school board members are elected by public. Board then hires/fires superintendent
- [Since June 2023](https://en.wikipedia.org/wiki/Houston_Independent_School_District_takeover): No local control. State-appointed Board. Governor hired the Superintendent, Chief Academic Officer, Chief Finance Officer
- New leadership, new priorities
- Stakeholder turnover, culture shocks, changes in every direction

## What's a public servant to do? 

- Teacher turnover > 30% annually
- Estimated > 75% churn in [principals](https://www.houstonchronicle.com/news/houston-texas/education/hisd/article/state-takeover-hisd-numbers-enrollment-principals-20199238.php) since takeover
- January 2025: Promotion! Project management for CFO
- Data-driven changes across areas of finance, operations, facilities, warehouse/distribution, real estate, accounts payable

## 



